version: "2"

services:
    app-server:
        image: wsucs3620/alpine-nginx-php7:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - /Users/donbstringham/Sandbox/wsucs3620/final-official/src:/usr/share/nginx
        links:
            - mysql:mysql
            - redis:redis
        depends_on:
            - mysql
            - redis

    mysql:
        image: wsucs3620/alpine-mysql:latest
        ports:
            - 3306:3306
        volumes:
            - /Users/donbstringham/Sandbox/wsucs3620/data/mysql:/data
        environment:
            - MYSQL_ROOT_PASSWORD=changeme
            - MYSQL_DATABASE=cs3620
            - MYSQL_USER=foo
            - MYSQL_PASSWORD=bar

    redis:
        image: wsucs3620/alpine-redis:latest
        ports:
            - 6379:6379
        volumes:
- /Users/donbstringham/Sandbox/wsucs3620/data/redis:/data